​deployment:
tasks:
- export DEPLOYPATH=/repositories/itclub.acc.edu.bd
- /bin/cp -R . $DEPLOYPATH
- cd $DEPLOYPATH
- /usr/local/bin/npm install
- /usr/local/bin/npm run build
- /usr/local/bin/npm start
